require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  # "고치면 바로 반영해!"
  config.enable_reloading = true

  # Do not eager load code on boot.
  # 필요할 때만 로딩해!
  config.eager_load = false

  # Show full error reports.
  # "에러가 뜨면 전부 보여줘!"
  config.consider_all_requests_local = true

  # Enable server timing.
  # "서버 시간을 보여줘!"
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  # 캐싱을 쓰면 성능이 좋아지지만, 개발할 때는 캐싱을 끄는 것이 좋음
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  # 캐싱을 쓰지 않음
  # 그냥 컴퓨터 RAM(메모리) 에 저장합니다. 서버 끄면 다 날아갑
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  # 파일을 로컬 파일 시스템에 저장
  # 업로드된 파일을 AWS S3 같은 곳이 아니라, 내 컴퓨터의 storage/ 폴더에 저장
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  # 메일이 보내지 않아도 됨
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  # 템플릿이 변경되면 즉시 반영
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  # 메일 템플릿에서 사용된 링크가 localhost를 사용
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  # 뷰 파일이 렌더링된 후에 파일 이름을 추가
  # HTML 주석으로 <!-- BEGIN app/views/users/new.html.erb --> 처럼
  # 어떤 파일이 렌더링되고 있는지 표시
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
